### ISSUE TITLE
[feature] 하단 네비게이션 바

### ISSUE THREAD

**Issue by mangmuse** [f-lab-edu/fit-planner#3]
## 🚀 Description
하단 네비게이션 바 라우팅 설정과 스타일링 및 테스트

![image](https://github.com/user-attachments/assets/3a794747-9bdc-449d-9b5b-b3c6e6d92451)

## ✅ Todo

- [x] 기본 스타일링 및 UI 디자인
- [x] 버튼 클릭 시 경로 이동 라우팅 설정
- [ ] 테스트 코드 작성

**Comment by f-lab-kevin** [comment]
라우팅 시 렌더링 방식은 페이지 별로 어떻게 정할것인지 방향성도 같이 적혀있으면 좋을것 같습니다!
